/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __sensor_messages_LaserScan_hpp__
#define __sensor_messages_LaserScan_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include "common_messages/Header.hpp"

namespace sensor_messages
{

class LaserScan
{
    public:
        common_messages::Header header;

        /**
         * timestamp in the header is the acquisition time of
         * the first ray in the scan.
         *
         * in frame frame_id, angles are measured around
         * the positive Z axis (counterclockwise, if Z is up)
         * with zero angle being forward along the x axis
         */
        float      angle_min;

        /// start angle of the scan [rad]
        float      angle_max;

        /// end angle of the scan [rad]
        float      angle_increment;

        /// angular distance between measurements [rad]
        float      time_increment;

        /**
         * time between measurements [seconds] - if your scanner
         * is moving, this will be used in interpolating position
         * of 3d points
         */
        float      scan_time;

        /// time between scans [seconds]
        float      range_min;

        /// minimum range value [m]
        float      range_max;

        /// maximum range value [m]
        int32_t    num_ranges;

        std::vector< float > ranges;

        /// range data [m] (Note: values < range_min or > range_max should be discarded)
        std::vector< float > intensities;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "LaserScan"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int LaserScan::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int LaserScan::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int LaserScan::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t LaserScan::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* LaserScan::getTypeName()
{
    return "LaserScan";
}

int LaserScan::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->header._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->angle_min, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->angle_max, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->angle_increment, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->time_increment, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->scan_time, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->range_min, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->range_max, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_ranges, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_ranges > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->ranges[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_ranges > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->intensities[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int LaserScan::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->header._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->angle_min, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->angle_max, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->angle_increment, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->time_increment, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->scan_time, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->range_min, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->range_max, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_ranges, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_ranges) {
        this->ranges.resize(this->num_ranges);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->ranges[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_ranges) {
        this->intensities.resize(this->num_ranges);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->intensities[0], this->num_ranges);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int LaserScan::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->header._getEncodedSizeNoHash();
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->num_ranges);
    enc_size += __float_encoded_array_size(NULL, this->num_ranges);
    return enc_size;
}

uint64_t LaserScan::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == LaserScan::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, LaserScan::getHash };

    uint64_t hash = 0xdd9a7c513e2fad48LL +
         common_messages::Header::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
