/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __robot_messages_VersionInfo_hpp__
#define __robot_messages_VersionInfo_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>

namespace robot_messages
{

class VersionInfo
{
    public:
        std::string hardware;

        /// <major>.<minor>.<patch>
        std::string firmware;

        /// <major>.<minor>.<patch>
        std::string software;

        /// Still to decide how it will look
        int32_t    udid[32];

        /// Bitmask that specifies the available features in the firmware and/or driver
        int64_t    features;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "VersionInfo"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int VersionInfo::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int VersionInfo::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int VersionInfo::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t VersionInfo::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* VersionInfo::getTypeName()
{
    return "VersionInfo";
}

int VersionInfo::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* hardware_cstr = const_cast<char*>(this->hardware.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &hardware_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* firmware_cstr = const_cast<char*>(this->firmware.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &firmware_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    char* software_cstr = const_cast<char*>(this->software.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &software_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->udid[0], 32);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->features, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int VersionInfo::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __hardware_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__hardware_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__hardware_len__ > maxlen - pos) return -1;
    this->hardware.assign(
        static_cast<const char*>(buf) + offset + pos, __hardware_len__ - 1);
    pos += __hardware_len__;

    int32_t __firmware_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__firmware_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__firmware_len__ > maxlen - pos) return -1;
    this->firmware.assign(
        static_cast<const char*>(buf) + offset + pos, __firmware_len__ - 1);
    pos += __firmware_len__;

    int32_t __software_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__software_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__software_len__ > maxlen - pos) return -1;
    this->software.assign(
        static_cast<const char*>(buf) + offset + pos, __software_len__ - 1);
    pos += __software_len__;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->udid[0], 32);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->features, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int VersionInfo::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->hardware.size() + 4 + 1;
    enc_size += this->firmware.size() + 4 + 1;
    enc_size += this->software.size() + 4 + 1;
    enc_size += __int32_t_encoded_array_size(NULL, 32);
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t VersionInfo::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x9fb64c7945614fb5LL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
